### ISSUE TITLE
Extend catalog with filters

### ISSUE THREAD

**Issue by hcvdwerf** [GenomicDataInfrastructure/gdi-userportal-frontend#10]
## What

As user I want to filter my datasets.

## Tasks
* Make filter a reusable angular component
* Remove filter input field
* Add `Formats`, `Catalogues`, `Themes` and `Keywords`
* Integrate it with the backend

**Comment by hcvdwerf** [comment]
Format

**Comment by brunopacheco1** [comment]
I would suggest we use `data.europa.eu` as a model, on filters definition and on their labels as well.

<img width="1627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1734bd55b886ad1de0dc15b30da407e266e5064/image.png" alt="image.png" />

**Comment by hcvdwerf** [comment]
The image is not viewable

**Comment by hcvdwerf** [comment]
API documentation: API guide — CKAN 2.10.3 documentation 
Example search query (looking for datasets about “boom” (Dutch word for tree 🌳): https://ckan.dataplatform.nl/api/3/action/package_search?q=boom&sort=metadata_modified desc
json api makes it pretty clear what we can sort on

**Comment by brunopacheco1** [comment]
@admy7 This bug was found. `TypeError: undefined is not an object (evaluating 'd.theme[0]') (edited)`, should we open a new issue or would you work on it directly on this one?
