### ISSUE TITLE
[gdi - frontend] Improvements on the front end

### ISSUE THREAD

**Issue by nolliia** [GenomicDataInfrastructure/gdi-userportal-frontend#183]
### 🎯 What? (Story Description)

- align both the home page and datasets page on the same screen transformation
- make pagination on the left side of the dataset card column (now it's in the middle)
- make pagination dropdown in the top of the dataset page
- drop down the search bar to be in the same window as the dataset cards align

### 💡 Why? (Justification)

to improve the look and feel of the GDI portalGDI

### 🔨 Tasks (Breakdown)

suggest to the team how the changes will look like before the implementation

### ✅ Acceptance Criteria

are both the homepage and dataset page are aligned?
is pagination fixed? 

### ➕ Additional Information

<img width="1847" alt="Screenshot 2024-04-09 at 09 40 06" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/b12eb542-d082-4af5-a8b2-d872e615c667">
<img width="1854" alt="Screenshot 2024-04-09 at 09 40 21" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/3890e8b2-97ce-4722-b5a1-e714bbdd91d9">
<img width="870" alt="Screenshot 2024-04-09 at 09 40 49" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/e82e88ae-70b6-40de-8b2a-199321f5a1f6">
<img width="853" alt="Screenshot 2024-04-09 at 09 41 11" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/10a53a6a-882f-4765-8039-112a3f9b81e8">
<img width="706" alt="Screenshot 2024-04-09 at 09 41 25" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/73106409/0384dad7-2505-4ee2-ac15-2d77bb2e4540">

**Comment by brunopacheco1** [comment]
I will close this item, as we are reviewing the User Portal UX as a whole.
