### ISSUE TITLE
[gdi - frontend] Generify 4xx and 5xx error detail handling from backend

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#239]
### 🎯 What? (Story Description)

Generify 4xx and 5xx error detail handling from backend.

### 💡 Why? (Justification)

We should have a single Alert component that presents 4xx and 5xx `error.detail`, and `error.errorMessages` from backend.
We must present 4xx and 5xx error detail coming from access management service and dataset discovery service.

### 🔨 Tasks (Breakdown)

- Generify `Alert` component to be called/updated from different pages and components
- Change every call to backend to handle 4xx and 5xx and redirect `ErrorResponse` to `Alert`
- Remove from frontend `errorMessage` parsing.

### ✅ Acceptance Criteria

- Do we have a generic alert component?
- Are 4xx and 5xx error details displayed properly?

**Comment by brunopacheco1** [comment]
Hey @inderps , I was testing and I found this issue:

The alert is displayed several times, after navigating from one page to another.

<img width="1553" alt="Screenshot 2024-07-05 at 21 58 09" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/22e10f53-36c2-4583-a1e9-c1f7e4a16aa8">

To reproduce:

Add dataset 5397b3a0-faf6-4aae-873d-35088f8ec224 and 5397b3a0-faf6-4aae-873d-35088f8ec224 to basket

Click on request now

Navigate to Applications

**Comment by brunopacheco1** [comment]
The layout of the alert in `Dataset details` page is not correct. 

<img width="1567" alt="image" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/0d44559c-3a1f-4994-95d6-900ab77c49a2">

**Comment by brunopacheco1** [comment]
Regarding the error `Application Not Found`, the backend retrieves 404 and detail `Application 1900 not found`. Somewhere a server-side component the 404 is transformed into 500, with a different message.

<img width="933" alt="Screenshot 2024-07-05 at 22 04 18" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/2750c153-54db-4855-a976-07a5ae7c477e">

**Comment by inderps** [comment]
@brunopacheco1 Regarding Application Not Found, it is now seems to be throwing 404 correctly without me making any changes. Not sure why it was throwing 500 previously

<img width="1173" alt="Screenshot 2024-07-06 at 00 59 32" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/1210046/763ca4d8-5cd5-4ac6-9ee8-9e354e7b59e2">

**Comment by inderps** [comment]
Regarding the first issue you reported, would you mind reproducing it and probably providing me the steps.

Right now I'm not able to reproduce

https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/1210046/60ca85ba-7e86-417a-8a15-e6a31b74bc7a

**Comment by brunopacheco1** [comment]
You have to add two datasets, like I explained before, then you click on `Request now`. 

`bc7664b4-284a-44c0-9ce8-bc3d6882e7fe` and `5397b3a0-faf6-4aae-873d-35088f8ec224`, for example.

**Comment by brunopacheco1** [comment]
I just realised I did not deployed latest changes. One moment...
