### ISSUE TITLE
Add distributions to Dataset Details view

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#26]
## What

Add distributions to Dataset Details view.

## Why

So we can see the whole dataset details.

## Acceptance Criteria
- Can I see all distributions of a dataset?
- Are all fields from distribution displayed?

## Tasks
- Define layout and discuss with team.
- Implement proposed design.

## Attachments
<img width="1725" alt="Screenshot 2023-12-29 at 11 31 46" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/5ea47580-55c5-4d7d-904c-465b7cba2af7">

**Comment by hcvdwerf** [comment]
Forward this question to my team to check their opinion about this issue.

**Comment by brunopacheco1** [comment]
This is an example with a few datasets and lots of distributions. https://portal-gdi-nl.molgeniscloud.org/apps/central/#/
