### ISSUE TITLE
[GDI - frontend] Show top themes used in User Portal on Home View

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#27]
## What

Show top themes used in User Portal on Home View.

## Why

We have more visible content in the home view.

## Acceptance Criteria
- Do I see the top themes used by the User Portal on the Home View?

## Tasks
- Discuss and define layout of the new section on the Home View.
- Implement changes.

## Attachments

<img width="1728" alt="image" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/f3dcda39-8b3f-412a-acaf-ea44d442767c">

**Comment by hcvdwerf** [comment]
Forward this question to my team to check their opinion about this issue.
