### ISSUE TITLE
[gdi - frontend] Remove publisher picture

### ISSUE THREAD

**Issue by nolliia** [GenomicDataInfrastructure/gdi-userportal-frontend#386]
### 🎯 What? (Story Description)
Remove publishers pictures.

### 💡 Why? (Justification)
Publishers may come from several different sources, and we cannot control where the image will come from.

### 🔨 Tasks (Breakdown)
- remove picture from publishers
- improve layout and design if needed.

### ✅ Acceptance Criteria
- are all the requirements developed?

**Comment by zalborzi** [comment]
Can we have the name of "Organization" from a env var?
