### ISSUE TITLE
[GDI - frontend] Design granted datasets page in a tabbed view

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#60]
## What
Design user profile page.

## Why
So we can display granted-access datsets, list applications and other user details in a single place.

## Tasks
- Design and propose a user profile page
- Minimum features are:
  - Basic user details (Name, Org?, email, session id)
  - Granted Datasets list (name linked to link within portal to `/datasets/{id}', credential status, last modification date)
  - List of applications
  - Easy to find in toolbar
- Ensure the feature is responsive.

## Acceptance Criteria
- Are the minimum features discribed in the new design?
- Is the new feature responsive?

**Comment by brunopacheco1** [comment]
@admy7 I think you renamed the URLs, but you forgot to fix the `/applications/{id}`.
<img width="1587" alt="image" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/c22feffb-6ec1-4769-9ecc-ca206a88ee52">

**Comment by admy7** [comment]
Good catch @brunopacheco1. I can take a look to fix it

**Comment by brunopacheco1** [comment]
@admy7 Tomorrow morning, in the first hour. ;P
