### ISSUE TITLE
[GDI - frontend] Design applications page

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#61]
## What
Design applications page.

## Why
So we can use the design to implement the new applications page.

## Tasks
- Design and propose a applications page
- Minimum features are:
  - List user's previously submitted applications, with minimum data (application id linked to the application in REMS?, latest status, latest modification date, and reasons/message?).
  - Resubmit button for rejected or revoked applications.
  - Cancel button for pending applications.
- Route page to `/my-applications`.
- Ensure the feature is responsive.

## Acceptance Criteria
- Are the minimum features discribed in the new design?
- Is the new feature responsive?

**Comment by EmiPali** [comment]
Design: https://excalidraw.com/#json=Zt5n0rpvfbH-LFepyyEh5,g12APNsRysbK9ZTVUa0KJA
