### ISSUE TITLE
Extend catalog with sorting

### ISSUE THREAD

**Issue by hcvdwerf** [GenomicDataInfrastructure/gdi-userportal-frontend#9]
## What

As user I want to sort the datasets.

## Tasks

* Add a search header element
* Display `Datasets found (%s)`
* Add sort by: `Last created`, `Last modified`, `Name ascending`, `Name descending`, `Relevance` (default).
* Integrate sorting with backend

Example from `data.europa.eu`:
<img width="833" alt="Screenshot 2023-12-13 at 10 04 17" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/assets/4491850/afc8bf52-0a45-47ef-87fc-f708c136afcc">

**Comment by brunopacheco1** [comment]
I would again suggest to follow `data.europa.eu` as a model. We could also display to total counter on the top, like the print screen.

<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE5XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6247f79c255e3214013aaf3c578ebf8d8eb1f11b/image.png" alt="image.png" />
