### ISSUE TITLE
[GDI - frontend] Develop dataset details page

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-frontend#94]
### 🎯 What? (Story Description)

Develop dataset details page.

This story is blocked by:
- https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/issues/56
- https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/issues/35
- https://github.com/GenomicDataInfrastructure/gdi-userportal-frontend/issues/39

### 💡 Why? (Justification)

So the user can see the details of a dataset.

### 🔨 Tasks (Breakdown)

- Develop a dataset details page.
- Add tests if needed/possible.
- Add datasets page as the `/datasets/{id}` in the routing components.
- Ensure the URL routing is still working when the app is deployed in a container that.
- Ensure the feature is responsive.

### ✅ Acceptance Criteria

- Is the datasets details page similar to the current implementation?
- Is the new feature responsive?

**Comment by admy7** [comment]
This looks like the acceptance criteria of the dataset search page.

This may rather be: 

- Does the page provide all the necessary information about the dataset?
- Is the URL routing correct? 
- Is the page responsive?
